### ISSUE TITLE
Little Typo in n2k_nmea0183_transform.cpp

### ISSUE THREAD

**Issue by hwater** [hatlabs/SH-wg-firmware#15]
Hello Matti

there is an typo in line 274:
 tN2kAISTransceiverInfo ais_info;

it should read
  tN2kAISTransceiverInformation ais_info;

is this right? after this it compiles....

greeting - holger

**Comment by mairas** [comment]
This is right! This was due to changes in the upstream NMEA2000 library. There was an open PR about this very issue which I had forgotten to merge. Fixed now - thank you for the reminder!

**Comment by mairas** [comment]
Could you please open a new issue fo you have a specific problem. But please note that I won't be able to support running this firmware on any other hardware than the SH-wg.
